-- GPS reports are append-only history. The device writes only through the
-- gps-ingest Edge Function; browser clients receive read-only access via RLS.
create table if not exists public.gps_history (
  id bigint generated by default as identity primary key,
  event_id uuid not null,
  sequence_number bigint,
  device_id text,
  vehicle_id text not null,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m real,
  vertical_accuracy_m real,
  speed_kmh real,
  speed_accuracy_mps real,
  bearing_deg real,
  bearing_accuracy_deg real,
  derived_course_deg real,
  heading_source text,
  altitude_m real,
  battery_percent smallint,
  external_power boolean,
  battery_temperature_c real,
  thermal_status text,
  provider text,
  satellites_visible smallint,
  satellites_used smallint,
  constellations text,
  frequency_bands text,
  cn0_median_dbhz real,
  fix_rate_hz real,
  ttff_ms bigint,
  quality_state text,
  motion_state text,
  elapsed_realtime_nanos bigint,
  source text not null default 'unknown',
  source_recorded_at timestamptz not null,
  received_at timestamptz not null default now()
);

alter table public.gps_history add column if not exists event_id uuid;
alter table public.gps_history add column if not exists sequence_number bigint;
alter table public.gps_history add column if not exists device_id text;
alter table public.gps_history add column if not exists vehicle_id text;
alter table public.gps_history add column if not exists latitude double precision;
alter table public.gps_history add column if not exists longitude double precision;
alter table public.gps_history add column if not exists accuracy_m real;
alter table public.gps_history add column if not exists vertical_accuracy_m real;
alter table public.gps_history add column if not exists speed_kmh real;
alter table public.gps_history add column if not exists speed_accuracy_mps real;
alter table public.gps_history add column if not exists bearing_deg real;
alter table public.gps_history add column if not exists bearing_accuracy_deg real;
alter table public.gps_history add column if not exists derived_course_deg real;
alter table public.gps_history add column if not exists heading_source text;
alter table public.gps_history add column if not exists altitude_m real;
alter table public.gps_history add column if not exists battery_percent smallint;
alter table public.gps_history add column if not exists external_power boolean;
alter table public.gps_history add column if not exists battery_temperature_c real;
alter table public.gps_history add column if not exists thermal_status text;
alter table public.gps_history add column if not exists provider text;
alter table public.gps_history add column if not exists satellites_visible smallint;
alter table public.gps_history add column if not exists satellites_used smallint;
alter table public.gps_history add column if not exists constellations text;
alter table public.gps_history add column if not exists frequency_bands text;
alter table public.gps_history add column if not exists cn0_median_dbhz real;
alter table public.gps_history add column if not exists fix_rate_hz real;
alter table public.gps_history add column if not exists ttff_ms bigint;
alter table public.gps_history add column if not exists quality_state text;
alter table public.gps_history add column if not exists motion_state text;
alter table public.gps_history add column if not exists elapsed_realtime_nanos bigint;
alter table public.gps_history add column if not exists source text;
alter table public.gps_history add column if not exists source_recorded_at timestamptz;
alter table public.gps_history add column if not exists received_at timestamptz default now();

create unique index if not exists gps_history_event_id_key
  on public.gps_history (event_id);
create index if not exists gps_history_vehicle_recorded_idx
  on public.gps_history (vehicle_id, source_recorded_at desc);

create table if not exists public.vehicle_positions (
  vehicle_id text primary key,
  gps_history_id bigint references public.gps_history(id) on delete set null,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m real,
  speed_kmh real,
  bearing_deg real,
  altitude_m real,
  battery_percent smallint,
  speed_accuracy_mps real,
  bearing_accuracy_deg real,
  derived_course_deg real,
  heading_source text,
  quality_state text,
  motion_state text,
  sequence_number bigint,
  device_id text,
  external_power boolean,
  battery_temperature_c real,
  thermal_status text,
  satellites_used smallint,
  frequency_bands text,
  source_recorded_at timestamptz not null,
  received_at timestamptz not null default now()
);

alter table public.gps_history enable row level security;
alter table public.vehicle_positions enable row level security;

alter table public.vehicle_positions add column if not exists satellites_used smallint;
alter table public.vehicle_positions add column if not exists frequency_bands text;
alter table public.vehicle_positions add column if not exists speed_accuracy_mps real;
alter table public.vehicle_positions add column if not exists bearing_accuracy_deg real;
alter table public.vehicle_positions add column if not exists derived_course_deg real;
alter table public.vehicle_positions add column if not exists heading_source text;
alter table public.vehicle_positions add column if not exists quality_state text;
alter table public.vehicle_positions add column if not exists motion_state text;
alter table public.vehicle_positions add column if not exists sequence_number bigint;
alter table public.vehicle_positions add column if not exists device_id text;
alter table public.vehicle_positions add column if not exists external_power boolean;
alter table public.vehicle_positions add column if not exists battery_temperature_c real;
alter table public.vehicle_positions add column if not exists thermal_status text;

drop policy if exists "Public can read GPS history" on public.gps_history;
create policy "Public can read GPS history"
  on public.gps_history for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can read latest vehicle positions" on public.vehicle_positions;
create policy "Public can read latest vehicle positions"
  on public.vehicle_positions for select
  to anon, authenticated
  using (true);

revoke insert, update, delete on public.gps_history from anon, authenticated;
revoke insert, update, delete on public.vehicle_positions from anon, authenticated;
grant select on public.gps_history to anon, authenticated;
grant select on public.vehicle_positions to anon, authenticated;
